### ISSUE TITLE
Feature Request: TSX/JSX file type support

### ISSUE THREAD

**Issue by frdwhite24** [chrisgrieser/nvim-puppeteer#1]
### Feature Requested

The same functionality but for tsx and jsx file types, it works great in `.ts` but can't replicate in `.tsx`, happy to contribute if you can point me in the right direction!

P.S. fantastic work! 

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by frdwhite24** [comment]
Ah, i see that you've [commented on your reddit post](https://www.reddit.com/r/neovim/comments/16mmp80/comment/k19mlej/?utm_source=share&utm_medium=web2x&context=3) about already adding them. Looking at Lazy it indicates that it only loads on javascript, typescript and python filetypes. I suspect you'll also need to update the startup command for when it's loaded?

![image](https://github.com/chrisgrieser/nvim-puppeteer/assets/62175142/24146775-b6ef-4e57-9d68-d26e3e5286f6)

**Comment by frdwhite24** [comment]
for those running into this too, simply add the extra filetypes to the config provided in the readme. 

```
    ft = { "python", "javascript", "typescript", "typescriptreact", "javascriptreact" },
```

@chrisgrieser I'd recommend maybe keeping a list of supported file types somewhere, or linking to where it's captured in the code in the readme so people can see 😊 thanks for a great plugin!

**Comment by chrisgrieser** [comment]
oh true, forgot about that. thanks
