### ISSUE TITLE
[Bug]: replaceNodeText sometimes called with wrong end_row

### ISSUE THREAD

**Issue by MoritzBoehme** [chrisgrieser/nvim-puppeteer#11]
### Bug Description

I have had this issue for a while now, that when I rename a variable in a large python files via python-lsp-server I get the following error.
I could not yet reproduce this error for smaller python files.
```
Renamed 1 instance in 1 file
Error detected while processing TextChanged Autocommands for "<buffer=2>":
Error executing lua callback: ...-puppeteer-unstable-2023-11-13_1a941a8/lua/puppeteer.lua:10: Invalid 'end_row': out of range
stack traceback:
        [C]: in function 'nvim_buf_set_text'
        ...-puppeteer-unstable-2023-11-13_1a941a8/lua/puppeteer.lua:10: in function 'replaceNodeText'
        ...-puppeteer-unstable-2023-11-13_1a941a8/lua/puppeteer.lua:93: in function <...-puppeteer-unstable-2023-11-13_1a941a8/lua/puppeteer.lua:70>
```
I have also updated my treesitter grammars, but the error persists.
In my current config I am using inc-rename.nvim to rename the variable, but I just tried the native `vim.lsp.buf.rename()` as well, which also throws the same error.

### To Reproduce

Will try to add a minimal config and file which triggers this issue.

### neovim version

```Text
NVIM v0.10.0-dev-9dc4404
Build type: Release
LuaJIT 2.1.1693350652

and

NVIM v0.10.0-dev-7ca2d64
Build type: Release
LuaJIT 2.1.1693350652
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
yeah, I think that has to do with Treesitter simply choking on files that are too large. I'm afraid there is little I can do on my side there, sorry.
