### ISSUE TITLE
[Bug]: Converting python raw-string to f-string

### ISSUE THREAD

**Issue by z775729168** [chrisgrieser/nvim-puppeteer#12]
### Bug Description

The plugin will convert a python raw-string to a f-string.
https://github.com/chrisgrieser/nvim-puppeteer/blob/1a941a8684b937295632bc156d1b17e80de2d717/lua/puppeteer.lua#L88-L89
I change it to 
```lua
	local isFString = text:find("^[(f)(rf)]")
	local hasBraces = text:find("[^(\\x)]{.-[^%d,]+.-}")
```
not sure if this will fix all situations.

### To Reproduce

`"\d{3}"` -> `f"\d{3}"`

### neovim version

```Text
NVIM v0.10.0-dev-8405649
Build type: RelWithDebInfo
LuaJIT 2.1.1697887905
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
1. If you have a fix already, why not make a PR?
2. I am not certain I understand what your proposed changes are supposed to do. 
- Why `[(f)(rf)]` ?  
- regarding `[^(\\x)]`, I think lua patterns do not work that way, this will not correctly reject cases with a leading `\x`. 
- disallowing things like `{3}` makes sense, I haven't thought about strings that are regexes. However, it is not clear to me what the `,` is supposed to achieve here: `[^%d,]`.

**Comment by chrisgrieser** [comment]
okay, I have implemented changes that should mostly cover this.
