### ISSUE TITLE
Feature Request: support SvelteJS and/or add a filetype option

### ISSUE THREAD

**Issue by gbcreation** [chrisgrieser/nvim-puppeteer#13]
### Feature Requested

Thank you very much for this plugin.

Could you please support the `svelte` filetype with templateStr ?

It would also be very useful to have an configuration option to define which filetypes are enabled.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
I added svelte.

> It would also be very useful to have an configuration option to define which filetypes are enabled.
Good idea, done. (see Readme)

**Comment by gbcreation** [comment]
Thank you!
