### ISSUE TITLE
Feature Request: Add an option to set the quote style to use

### ISSUE THREAD

**Issue by gbcreation** [chrisgrieser/nvim-puppeteer#14]
### Feature Requested

Given this JS code:

```javascript
const test = `test ${myVar}`;
//                ^ cursor is here
```

With cursor on the space character in the template string, I press dt` and get:

```javascript
const test = "test";
```

I prefer to get:

```javascript
const test = 'test';
```

Could you please add a configuration option to set the quote style to use ?

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
implemented. Use `vim.g.puppeteer_js_quotation_mark`

**Comment by gbcreation** [comment]
Thank you
