### ISSUE TITLE
Bug: 'neo-tree' is not a  valid language name

### ISSUE THREAD

**Issue by mhellstr** [chrisgrieser/nvim-puppeteer#19]
### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read the README.
- [X] All Treesitter parsers for the filetypes used by nvim-puppeteer are installed,  and I updated all my Treesitter parsers via `:TSUpdate`.

### Bug Description

I'm unsure if this is an issue with neotree or puppeteer, but if I disable puppeteer there is no problem. The issue is triggered when opening neotree for a buffer outside the current cwd, when a .lua file is open.

### To Reproduce

```
cd ~/temp
nvim
:e ~/.config/nvim/init.lua
:Neotree %
Change cwd? y
```

Error executing vim.schedule lua callback: ...nux64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'neo-tree' is not a 
valid language name                                                                                                             
stack traceback:                                                                                                                
        [C]: in function 'error'                                                                                                
        ...nux64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: in function 'add'                                      
        ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:111: in function 'new'                                      
        /opt/nvim-linux64/share/nvim/runtime/lua/vim/treesitter.lua:41: in function '_create_parser'                            
        /opt/nvim-linux64/share/nvim/runtime/lua/vim/treesitter.lua:108: in function 'get_parser'                               
        /opt/nvim-linux64/share/nvim/runtime/lua/vim/treesitter.lua:386: in function 'getNodeAtCursor'                          
        .../.local/share/nvim/lazy/nvim-puppeteer/lua/puppeteer.lua:105: in function ''                                         
        vim/_editor.lua: in function ''                                                                                         
        vim/_editor.lua: in function <vim/_editor.lua:0>  

My puppeteer config is
```
return {
	{
		"chrisgrieser/nvim-puppeteer",
		enabled = true,
		lazy = false, -- plugin lazy-loads itself. Can also load on filetypes.
	},
}
```

### neovim version

```Text
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

**Comment by chrisgrieser** [comment]
not 100% sure, since I don't use neotree, but from the error, I'd think neotree changes a buffer's filetype at some point, resulting in puppeteer's autocmds being triggered in buffers of the wrong filetype.

I added some checks that detach puppeteer's autocmds if run in a buffer with wrong filetype, which should most likely fix this issue.
