### ISSUE TITLE
Bug: the plugin does nothing

### ISSUE THREAD

**Issue by simonmandlik** [chrisgrieser/nvim-puppeteer#20]
### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read the README.
- [X] All Treesitter parsers for the filetypes used by nvim-puppeteer are installed,  and I updated all my Treesitter parsers via `:TSUpdate`.

### Bug Description

Hi, this is basically a "duplicate" of https://github.com/chrisgrieser/nvim-puppeteer/issues/18, pretty much the same issue.

I can't get `nvim-puppeteer` to work even with the recommended `minimal.lua` there.

### Relevant Screenshot

<img width="263" alt="image" src="https://github.com/user-attachments/assets/f6a2d263-650b-4a49-9e57-ad49a40079fb">

### To Reproduce

`minimal.lua`:
```lua
-- save as `minimal.lua`
local plugins = {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		main = "nvim-treesitter.configs",
		opts = {
			ensure_installed = { "javascript" },
			highlight = { enable = true },
		},
	},
	{ "chrisgrieser/nvim-puppeteer" },
}
--------------------------------------------------------------------------------
for _, name in ipairs { "config", "data", "state", "cache" } do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = "/tmp/nvim-debug/" .. name
end
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	local lazyrepo = "https://github.com/folke/lazy.nvim"
	vim.fn.system { "git", "clone", "--filter=blob:none", lazyrepo, "--branch=stable", lazypath }
end
vim.opt.runtimepath:prepend(lazypath)
require("lazy").setup(plugins)
```

Then run `nvim -u minimal.lua test.py` and type in insert mode the text from the screenshot. When exiting the insert mode, nothing happens.

### neovim version

```Text
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
```

**Comment by chrisgrieser** [comment]
yeah, that's a completely different issue. Simply a typo I made a few commits ago 🙈

fixed now
