### ISSUE TITLE
[Bug]: Doesn't respect multiline strings on js/ts

### ISSUE THREAD

**Issue by alvarosevilla95** [chrisgrieser/nvim-puppeteer#6]
### Bug Description

The plugin changes backticks to regular quotes on a multiline string when no interpolation is detected, which is a syntax error.

### To Reproduce

* Create a multiline string with backticks:
```
const multiline = `This is
a multiline string`
```

* Exit insert mode. It turns into
```
const multiline = "This is
a multiline string"
```

### neovim version

```Text
NVIM v0.9.1
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
thx, is fixed

**Comment by chrisgrieser** [comment]
while I was at it, I also added a small feature to automatically convert a regular string to a template string when adding a line break inside the string :)

**Comment by alvarosevilla95** [comment]
That was fast! And great feature to add! Thanks!! 🎉
