### ISSUE TITLE
[Bug]: Handling of dunder variables is broken

### ISSUE THREAD

**Issue by Popkornium18** [chrisgrieser/nvim-puppeteer#7]
### Bug Description

nvim-puppeteer breaks on f-strings containing dunder variables.

### To Reproduce

Example 1:
- Type `text = "hello from {__file__}"`
- Puppeteer does not add the `f`
- Add the `f` manually
- Puppeteer removes the `f`
- Workaround to fix is adding a space between `f ""` and removing the space

Example 2:
- Type a correct `text = f"hello from {__file__}"`
- Try to change message to `f"hi from {__file__}"`
- Puppeteer removes the `f`
- I didn't find a workaround

### neovim version

```Text
0.9.1
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
thx, fixed
